import { writeFileSync } from 'node:fs'

import st from 'opencc-js/dict/STCharacters'
import tw from 'opencc-js/dict/TWVariants'

// Characters in standard Big5 (A440-C67E, C940-F9D5, HKSCS left out) are used in Traditional text,
// so OpenCC pairs whose simplified side is one of them (台, 后, 干, 里) are not evidence of Simplified.
const big5 = new Set()
const decoder = new TextDecoder('big5')
const code = (lead, trail) => (lead << 8) | trail
const standard = c => (c >= 0xa440 && c <= 0xc67e) || (c >= 0xc940 && c <= 0xf9d5)
for (let lead = 0xa4; lead <= 0xf9; lead++)
  for (let trail = 0x40; trail <= 0xfe; trail++)
    if ((trail <= 0x7e || trail >= 0xa1) && standard(code(lead, trail))) big5.add(decoder.decode(new Uint8Array([lead, trail])))

const twVariants = new Map(tw.split('|').map(e => e.split(' ')))

const pairs = st
  .split('|')
  .map(e => e.split(' '))
  .filter(([s, t]) => t !== undefined && s !== t && !big5.has(s))
  .map(([s, t]) => s + (twVariants.get(t) ?? t))

writeFileSync(
  new URL('../hooks/vendor/hans.js', import.meta.url),
  `// Generated by scripts/build-hans.mjs from OpenCC STCharacters and TWVariants (Apache-2.0).\nexport default ${JSON.stringify(pairs.join('|'))}\n`,
)
